import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';
import { Instrument_Sans, Instrument_Serif, JetBrains_Mono } from 'next/font/google';

import './globals.css';

import { SmoothScroll } from '@/components/SmoothScroll';
import { Cursor } from '@/components/ui/Cursor';
import { Nav } from '@/components/site/Nav';
import { Footer } from '@/components/site/Footer';
import { PageTransition } from '@/components/ui/PageTransition';
import { Preloader } from '@/components/ui/Preloader';
import { Toaster } from '@/components/ui/Toast';

/**
 * TYPE
 *
 * One display face, one workhorse, one mono — the spec's "expressive display +
 * neutral sans" pairing, and the mono is the site's label voice (every eyebrow,
 * every house code, every price rail).
 *
 * Self-hosted through next/font, so the files are emitted into the static export
 * with the CSS that declares them: no request to a third party at runtime, no
 * layout shift from a late swap, and the display face can be preloaded because
 * the hero headline is the first thing painted.
 */
const display = Instrument_Serif({
  subsets: ['latin'],
  weight: '400',
  style: 'normal',
  display: 'swap',
  variable: '--font-display-face',
});

const sans = Instrument_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans-face',
});

const mono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mono-face',
});

export const metadata: Metadata = {
  metadataBase: new URL('https://frecom.example'),
  title: {
    default: 'Frecom — audio objects',
    template: '%s — Frecom',
  },
  description:
    'Frecom builds six audio objects and nothing else: headphones, loudspeakers, a turntable, an amplifier and a stand. Drawn, milled and assembled in one workshop.',
  applicationName: 'Frecom',
  keywords: [
    'headphones',
    'loudspeakers',
    'turntable',
    'amplifier',
    'hi-fi',
    'audio objects',
  ],
  openGraph: {
    type: 'website',
    siteName: 'Frecom',
    title: 'Frecom — audio objects',
    description:
      'Six audio objects, made slowly in one workshop. Studio-lit, rendered live.',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Frecom — audio objects',
    description:
      'Six audio objects, made slowly in one workshop. Studio-lit, rendered live.',
  },
  robots: { index: true, follow: true },
};

export const viewport: Viewport = {
  themeColor: '#0d0b09',
  colorScheme: 'dark',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${sans.variable} ${mono.variable}`}
    >
      <body>
        <a
          href="#main"
          className="eyebrow sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[110] focus:rounded-sm focus:bg-bone focus:px-4 focus:py-3 focus:text-ink"
        >
          Skip to content
        </a>

        <SmoothScroll />
        <Cursor />
        <Nav />

        <main id="main" className="relative">
          {children}
        </main>

        <Footer />

        <PageTransition />
        <Toaster />
        <Preloader />

        {/* Film grain over the whole document. Generated by the browser, hidden
            under reduced motion, and never in the way of a pointer. */}
        <div
          aria-hidden="true"
          className="grain-layer pointer-events-none fixed inset-0 z-[95] opacity-[0.045]"
        />
      </body>
    </html>
  );
}
